[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["jdao55 <joedao55@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
image = "0.22.2"
rayon = "1.2.0"
